[theme]
primaryColor="#FF4B4B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"

[browser]
gatherUsageStats = false

[server]
enableStaticServing = false
port = 8501
address = "localhost"
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
maxMessageSize = 200

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true

[logger]
level = "info" 